### ISSUE TITLE
Local Support

### ISSUE THREAD

**Issue by DesignSkeptic** [JuanJakobo/Pocketbook-Miniflux-Reader#4]
Can you add support for local RSS feeds (OPML File) so we don't have to use miniflux?

**Comment by JuanJakobo** [comment]
Hi, the Miniflux system is quite deeply integrated, therefore an integration of local RSS feeds would be a lot of work. Did you already try the installed RSS feed app or the koreader app?

**Comment by DesignSkeptic** [comment]
I had. They are closer to RSS Feed downloaders rather than RSS Feed readers. I would attempt a PR myself, but I'm not too familiar with working with C++.

**Comment by JuanJakobo** [comment]
What is the difference inbetween these two? What features do you require/expect?
